project: pimc
display_name: PIMC
domain: signal_processing/wireless
description: PIMC for FDD Massive MIMO under beam/layer switching.
tags:
  - PIM
  - routing
  - massive_mimo
  - FDD
  - beam_switching
